### ISSUE TITLE
ApproxMVBB library version could not be determined!, HEAD-HASH-NOTFOUND

### ISSUE THREAD

**Issue by thomas2108** [gabyx/ApproxMVBB#28]
Same in CMAKE 3.12.2 for Windows and Visual Studio 2017 (15.8.3)

Please help
![error](https://user-images.githubusercontent.com/6136259/45496882-b544a980-b776-11e8-9268-5006d32977f8.png)

**Comment by gabyx** [comment]
Did you download the zip, file and tried to build from that?
I think that might cause the issue, since there is no .git folder, hm... I should make a version file :-), and read from this if there is no ".git" folder

**Comment by thomas2108** [comment]
Yes, I downloaded the Zip. Can i do something?

**Comment by gabyx** [comment]
Fork the repository instead, and build it, then it works. Meaning, clone it in git

**Comment by thomas2108** [comment]
Done, have several issues:

AngleFunctions.hpp + MakeCoordinateSystem.hpp:  M_PI undefined
inserted 
```
#define _USE_MATH_DEFINES
#ifndef M_PI
#    define M_PI 3.14159265358979323846
#endif
```
before 
`#include <cmath>`

in xpfpa.h replaced
`#    elif HAVE__CONTROLFP_S`
with
`#    elif defined(HAVE__CONTROLFP_S)`

ApproxMVBB 32Bit Debug now builds, others still error….continue later

**Comment by gabyx** [comment]
Can you make  a PR when you manage to compile it with VS 17, thx!

**Comment by thomas2108** [comment]
I managed to build ApproxMVBB with VS17. VS2017 contains native CMAKE support and builds the lib directly now. Have .dll file and .lib file. But I'm not able to build example/approxMVBB . Linker is missing the library. I'm no CMAKE expert, don't know what to do. Can you assist ?
![unbenannt](https://user-images.githubusercontent.com/6136259/45687371-eba36f80-bb4e-11e8-9d94-6da7ce36af7a.png)

**Comment by gabyx** [comment]
Working on a solution for VS 15/17. I dont have 17, but should work as well

**Comment by gabyx** [comment]
Please try the branch: `msvc-compatibility`
It seems to compile under VS 15 so far.
```cmake -G "Visual Studio 14 2015 Win64" -DApproxMVBB_XML_SUPPORT=OFF -DApproxMVBB_KDTREE_SUPPORT=OFF <pathToCode>```

**Comment by gabyx** [comment]
Try the current master branch if it builds in VS 17

**Comment by adam-hartshorne** [comment]
I have problems using cmake to build a solution file. First I get the following error,

 ApproxMVBB library version could not be determined!

And can't get around that.

Second, the Find PugiXML_DIR is rather odd. Rather than wanting the base location or the location of the lib file, it wants the location of the _source_dir/CMakeFiles/Export/lib/cmakepugixml/ and for the compiled library to be in the Export/lib directory.

Third, why are we having to give the location of git.exe. Seems rather odd dependency.

**Comment by gabyx** [comment]
Ok, git is used for determining the version, I try to remove this need. When you installed PugiXML with cmake, the ApproxMVBB should find it, we do not provide  script for finding pugixml since by default it is found correctly with the default finding procedure in cmake since pugixml also supports this.
I update the docs so far, and pugixml is now by default disabled (`ApproxMVBB_XML_SUPPORT="OFF"`) on the master branch.

**Comment by gabyx** [comment]
As a remedy for now, clone the repo with `git`. Dont use the zip file...

**Comment by adam-hartshorne** [comment]
I am cloning with git.

**Comment by gabyx** [comment]
I updated, Git should now no more be needed, as long as you delete the .git folder: then the version is read from the version file `VERSION`.
